In [12]:
import autograd.numpy as np
from autograd import grad

In [4]:
theta = np.random.randn(2,1)
n = 1000
x = 2*np.random.rand(n,1)
y = 4+3*x+np.random.randn(n,1)

X = np.c_[np.ones((n,1)), x]

In [5]:
def cost(theta):
    return 1/n*((y-X@theta).T@(y-X@theta))

In [6]:
theta

array([[-1.53905607],
       [-1.32139946]])

In [7]:
gradients = 2.0/n*X.T @ ((X @ theta)-y)
gradients

array([[-19.72984398],
       [-22.67833673]])

In [8]:
grad2 = grad(cost)
theta
print(grad2(theta))

[[-19.72984398]
 [-22.67833673]]


What we see is that the cost function can simply be defined, and then autgrad can calculate gradients based on current theta. This can be useful in SGD. Would be nice if one could use MSE directly.

In [13]:
def MSE(z_data,z_model):
    '''
    Returns the MSE for z_data and z_model
    '''
    n = np.size(z_model)
    return np.sum((z_data-z_model)**2)/n

def cost(z_data, X, theta):
    return MSE(z_data,X@theta)

In [14]:
grad3 = grad(cost,2)

In [15]:
grad3(y,X,theta)

array([[-19.72984398],
       [-22.67833673]])

In [ ]:
theta2 = theta

In [ ]:
theta2 = theta2 - 0.01*grad3(y,X,theta2)
theta2